---
title: "macc_qa_qc"
author: "Bethel Cole-Smith"
date: "2025-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(ggplot2)
# devtools::install_github("aj-sykes92/ggmacc")
library(ggmacc)

# to do list
#1 - group sources into larger groups ex metals is made up of aluminum and magnesium - see slide 2 for all the IPPU groupings https://usepa.sharepoint.com/:p:/r/sites/oar_Work/globalnonco2report/_layouts/15/Doc.aspx?sourcedoc=%7B0F5C68DF-C860-406D-957B-82D71A64342E%7D&file=Sector-specific%20Methods%20Brief%20%232_IPPU_Waste_for%20CCD_010725.v1.pptx&wdLOR=c836DB07D-5567-4A92-BBEC-84771FAFF3FE&fromShare=true&action=edit&mobileredirect=true 



#2 - # TO DO 2: create different plots by state (once we get the country level data we can switch the variable to state)

#3 - # TO DO 3: create overall mitigation by each sector (one for Ag, one for energy, one for IPPU, one for waste)

#4 - # TO DO 4: create table showing total mitigation at or below zero and total mitigation (overall) ie a two line table for each source group (eg ODS Subs, Electronics, wastewater, oil and gas)

```

## R Markdown

```{r cars}

MACC_Gas_Tech_Dom_raw <- read_csv("MACC_Gas_Tech_Dom.csv")

unique(MACC_Gas_Tech_Dom_raw$source)
# "CROP" "LIVE" "RICE" "COL"  "GAS"  "AERO" "AL"   "EPS"  "FIRE" "FOAM" "MG" "NAA"  "PV"   "RAC"  "SEMI" "SOLV" "LAN"  "WWR"

# TO DO #1: group sources within IPPU into ODS Subs, Metals, etc
## For the 2024 data, may need to have a comparative group (ie one that only includes the subsources present in the 2019 data) and a full group (one that incorporates all the different subsources in 2024)

MACC_Gas_Tech_Dom_sorted <- MACC_Gas_Tech_Dom_raw %>%
  dplyr::filter(sector == "WASTE") %>%
  group_by(source, year) %>%
  arrange(p,.by_group = TRUE) %>% # must specifically mention .by_group = TRUE otherwise it will ignore the group_by
  mutate(cumulative_reduction = cumsum(q_total))

MACC_Gas_Tech_Dom_sorted %>%
  #filter(sector == "WASTE") %>%
  ggplot(aes(x = cumulative_reduction, y = p)) +
  geom_col() +
  #geom_rect(aes(xmin = , xmax = , )) +
  facet_grid(source~year, scales = "free") 
  
macc_prep_df <- MACC_Gas_Tech_Dom_sorted %>%
  macc_prep(mac = p, abatement = q_total) 


macc_prep_df %>%
  ggplot() +
  geom_rect(aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax, fill = tech)) +
  facet_wrap(~source)
  #geom_macc(fill = tech) +
  

# TO DO 2: create different plots by state (once we get the country level data we can switch the variable to state)

social_cost_of_carbon <- 66.1

full_macc <- MACC_Gas_Tech_Dom_sorted %>%
  ggmacc(abatement = q_total, mac = p, cost_threshold = 100,
         zero_line = TRUE, threshold_line = TRUE, threshold_fade = 0.3)
# fill = tech,
full_macc

view(uk_agroforestry)

#  different lines for different model_years (eg 2019 vs 2024 report)

MACC_Gas_Tech_Dom <- MACC_Gas_Tech_Dom_raw %>%
  group_by(source, year, p) %>%
  summarize(total = q_total)
  
  


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
# TO DO 3: create overall mitigation by each sector (one for Ag, one for energy, one for IPPU, one for waste)

MACC_sector_new <- MACC_Gas_Tech_Dom_raw %>%
  dplyr::filter(sector == "WASTE" & year == 2030) %>%
  group_by(source, year, p, tech_long) %>%
  summarize(q_total = sum(q_total)) %>%
  ungroup()

macc_prep_new <- MACC_sector_new %>%
  macc_prep(mac = p, abatement = q_total) 

macc_prep_new %>%
  ggplot() +
  geom_rect(aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax, fill = tech_long)) +
  facet_grid(year~source) +
  #ylim(min(macc_prep_sector_df_alt$p), max(macc_prep_sector_df_alt$p)) + 
  scale_fill_discrete(guide = guide_legend()) +
  theme(legend.position="bottom")

```



```{r additional}


MACC_sector <- MACC_Gas_Tech_Dom_raw %>%
  dplyr::filter(sector == "WASTE" & year == 2030) %>%
  group_by(source, year, p, tech_long) %>%
  summarize(price_specific_reduction = sum(q_total))

MACC_sector_cum <- MACC_sector %>%
  ungroup() %>%
  group_by(source, year) %>% # no longer grouping by tech_long or p, so that the cumulative mitigation can be cumulative over source and year, regardless of the technology being used, and regardless of the price. Meaning that it will sum up all the mitigation for a specific source, for a specific year (instead of only summing the mitigation for a source and year within a specific price and within a specific technology)
  arrange(p,.by_group = TRUE) %>% # must specifically mention .by_group = TRUE otherwise it will ignore the group_by
  mutate(cumulative_reduction = cumsum(price_specific_reduction))

check_MACC_sector_cum_totals <- MACC_sector %>%
  group_by(source, year) %>%
  summarize(total_mitigation = sum(price_specific_reduction))

check_MACC_sector_cum_totals_alt <- MACC_Gas_Tech_Dom_raw %>%
  dplyr::filter(sector == "WASTE" & year == 2030) %>%
  group_by(source, year) %>%
  summarize(total_mitigation = sum(q_total))
  
macc_prep_sector_df <- MACC_sector %>%
  macc_prep(mac = p, abatement = total_mitigation) 

macc_prep_sector_df_alt <- MACC_sector_cum %>%
  macc_prep(mac = p, abatement = total_mitigation) 


macc_prep_sector_df_alt %>%
  ggplot() +
  geom_rect(aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax, fill = tech_long)) +
  facet_grid(year~source) +
  #ylim(min(macc_prep_sector_df_alt$p), max(macc_prep_sector_df_alt$p)) + 
  scale_fill_discrete(guide = guide_legend()) +
  theme(legend.position="bottom")

plot_macc <- function(dataframe, source){
  dataframe %>%
    dplyr::filter(source == source) %>%
    ggplot() +
    geom_rect(aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax, fill = tech_long)) +
    facet_wrap(~year) +
    ylim(min(dataframe$p), max(dataframe$p)) + 
    scale_fill_discrete(guide = guide_legend()) +
    theme(legend.position="none")
}

plot_macc(macc_prep_sector_df, CROP)


plot_macc_alt <- function(dataframe, source){
  dataframe %>%
    dplyr::filter(source == source) %>%
    ggplot() +
    geom_rect(aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax, fill = tech_long)) +
    facet_wrap(~year) +
    ylim(min(dataframe$p), max(dataframe$p)) + 
    scale_fill_discrete(guide = guide_legend()) +
    theme(legend.position="none")
}

plot_macc_alt(macc_prep_sector_df_alt, WWR)
plot_macc_alt(macc_prep_sector_df_alt, LAN)

```




```{r pressure, echo=FALSE}


# TO DO 4: create table showing total mitigation at or below zero and total mitigation (overall) ie a two line table for each source group (eg ODS Subs, Electronics, wastewater, oil and gas)
  
  MACC_mitigation_alt <- MACC_Gas_Tech_Dom_raw %>%
  #dplyr::filter(sector == "WASTE") %>%
    #mutate(price_group = case_when(p <= 0 ~ "at or below zero",
    #                               p >0 ~ "above zero")) %>%
  group_by(source, year) %>%
  arrange(p,.by_group = TRUE) %>% # must specifically mention .by_group = TRUE otherwise it will ignore the group_by
  mutate(cumulative_reduction = cumsum(q_total),
         price_group = case_when(p <= 0 ~ "at or below zero",
                                   p >0 ~ "above zero"),
         price_group_ordered = factor(price_group, level = c("at or below zero", "above zero"))) %>%
  ungroup() %>%
    group_by(source, year, price_group_ordered) %>% 
    arrange(p,.by_group = TRUE) %>% 
  summarize(total_mitigation_by_price_group = sum(q_total)) %>%
    #ungroup() %>%
    #group_by(source, year) %>%
  #arrange(p,.by_group = TRUE) %>% # must specifically mention .by_group = TRUE otherwise it will ignore the group_by
  mutate(cumulative_reduction = cumsum(total_mitigation_by_price_group))
  #dplyr::filter(p == 0 | p == max(p))

```
